version: "3.8"
services:
  db:
    image: postgres:15
    container_name: task-manager-pgsql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
